Implement DTO classes
lukaszkosminski/crypto.app pull request #1
Opened 2023-02-11 16:35 UTC by lukaszkosminski

2023-02-18 19:17 UTC, Maciekek commented
please add .idea folder to .gitignore

2023-02-18 19:54 UTC, Maciekek requested changes

2023-02-18 19:54 UTC, Maciekek commented on src/main/java/com/cryptoapp/model/CryptoCurrency.java
> +    @CreationTimestamp
please add new line between fields

2023-02-18 19:54 UTC, Maciekek commented on src/main/java/com/cryptoapp/model/crypto/Ada.java
> +
too many new lines

2023-02-18 19:54 UTC, Maciekek commented on src/main/java/com/cryptoapp/Application.java
> +
redundant new line

2023-02-18 19:54 UTC, Maciekek commented on src/main/java/com/cryptoapp/controller/CryptoCurrencyController.java
> +        cryptoCurrencyRepository.save(CryptoCurrencyMapper.mapToCurrency(cryptoCurrencyDTO));
someone will say it is bad practice to call repository from controller. I would say, for VERY simple `save` it is ok, but I am pretty sure, this line will be more complex in future, and you will have to move it to service.

2023-02-18 19:54 UTC, Maciekek commented on src/main/java/com/cryptoapp/controller/CurrencyController.java
> +        return currencyService.mapAndSave(currencyDTO);
I would split `mapAndSave` into `map(..)` and `save(..)`, also form this article https://medium.com/learnwithnk/best-practices-in-spring-boot-project-structure-layers-of-microservice-versioning-in-api-cadf62bd3459, you should pass Model into service (after mapping), but you are passing DTO. I would say, it is better to map it before, but I am not sure about this

2023-02-18 19:54 UTC, Maciekek commented on src/main/java/com/cryptoapp/controller/CurrencyController.java
> +        return currencyService.mapAndSave(currencyDTO);
I think it is fine for now, but stick to this approach, we can change it later

2023-02-18 19:54 UTC, Maciekek commented on src/main/java/com/cryptoapp/controller/UserController.java
> +
too many new lines

2023-02-18 19:54 UTC, Maciekek commented on src/main/java/com/cryptoapp/controller/UserController.java
> +    @PutMapping("user/{idUser}/change-email/{newEmail}")
you should not sent `newEmail` in URL, please use body to pass this value

2023-02-18 19:54 UTC, Maciekek commented on src/main/java/com/cryptoapp/controller/UserController.java
> +    @DeleteMapping("user/{idUser}/delete")
you use delete method, so `/delete` in url is redundant

2023-02-18 19:54 UTC, Maciekek commented on src/main/java/com/cryptoapp/controller/UserController.java
> +    @PutMapping("user/{idUser}/wallet/{idWallet}")
do not pass crucial data in URL, it is not safe way to pass info do API, please use request body

2023-02-18 19:54 UTC, Maciekek commented on src/main/java/com/cryptoapp/controller/UserController.java
> +    @PostMapping("user/create")
According REST, you should call this endpoint as `users`

2023-02-18 19:54 UTC, Maciekek commented on src/main/java/com/cryptoapp/controller/UserController.java
> +
new lines

2023-02-18 19:54 UTC, Maciekek commented on src/main/java/com/cryptoapp/controller/WalletController.java
> +
new lines

2023-02-18 19:54 UTC, Maciekek commented on src/main/java/com/cryptoapp/controller/WalletController.java
> +        return walletService.getWalletList();
can I get wallets of ALL users? why so? it is safe?

2023-02-18 19:54 UTC, Maciekek commented on src/main/java/com/cryptoapp/controller/WalletController.java
> +        return walletService.mapAndSave(walletDTO);
Shouldn't wallet be assigned to the user?

2023-02-18 19:54 UTC, Maciekek commented on src/main/java/com/cryptoapp/dto/CryptoCurrencyDTO.java
> +
new lines

2023-02-18 19:54 UTC, Maciekek commented on src/main/java/com/cryptoapp/dto/CryptoCurrencyDTO.java
> +
new lines

2023-02-18 19:54 UTC, Maciekek commented on src/main/java/com/cryptoapp/model/CryptoCurrencyRate.java
> +    @CreationTimestamp
please add new lines between fields

2023-02-18 19:54 UTC, Maciekek commented on src/main/java/com/cryptoapp/service/CryptoCurrencyRateService.java
> +        String API_URL = String.format("https://min-api.cryptocompare.com/data/price?fsym=%s&tsyms=USD&api_key=57bf7cc844e4afd9d7ab7d87b7def9366f9208aa26f9d5d699662586b360cab1", symbol);
DO NOT PUT ANY API KEY IN CODE, IT IS AVAILABLE FOR ANYBODY FROM THE INTERNET

2023-02-18 19:54 UTC, Maciekek commented on src/main/java/com/cryptoapp/service/CryptoCurrencyRateService.java
> +        String API_URL = String.format("https://min-api.cryptocompare.com/data/price?fsym=%s&tsyms=USD&api_key=57bf7cc844e4afd9d7ab7d87b7def9366f9208aa26f9d5d699662586b360cab1", symbol);
this URL should be taken from some constants, api_key should be treated as secret, you shoudn't put it here

2023-02-18 19:54 UTC, Maciekek commented on src/main/java/com/cryptoapp/service/CryptoCurrencyRateService.java
> +        List<CryptoCurrencyRateDTO> cryptoCurrencyRateDTOList = new ArrayList<>();
empty <>?

2023-02-18 19:54 UTC, Maciekek commented on src/main/java/com/cryptoapp/service/CryptoCurrencyRateService.java
> +        List<CryptoCurrencyRateDTO> cryptoCurrencyRateDTOList = new ArrayList<>();
I think, I don't understand what you are doing here and why, probably because of missing understanding of domain of the app

2023-02-18 19:54 UTC, Maciekek commented on src/main/java/com/cryptoapp/service/CurrencyService.java
> +    public CurrencyDTO addQuantity(Long id, Integer add) {
I do not like this `add` name

2023-02-18 19:54 UTC, Maciekek commented on src/main/java/com/cryptoapp/service/CurrencyService.java
> +    public CurrencyDTO mapAndSave(CurrencyDTO currencyDTO) {
as mentioned above (earlier), I do not like any function called with AND, it means that this method is doing more than one thing

2023-02-18 19:54 UTC, Maciekek commented on src/main/java/com/cryptoapp/service/UserService.java
> +    public List<WalletDTO> getWalletByUser(Long idUser) {
getWallet**s**ByUser?

2023-02-19 18:57 UTC, lukaszkosminski commented on src/main/java/com/cryptoapp/model/CryptoCurrency.java
> +    @CreationTimestamp
done

2023-02-19 18:57 UTC, lukaszkosminski commented on src/main/java/com/cryptoapp/model/crypto/Ada.java
> +
done

2023-02-19 18:57 UTC, lukaszkosminski commented on src/main/java/com/cryptoapp/Application.java
> +
done

2023-02-19 18:59 UTC, lukaszkosminski commented on src/main/java/com/cryptoapp/controller/CryptoCurrencyController.java
> +        cryptoCurrencyRepository.save(CryptoCurrencyMapper.mapToCurrency(cryptoCurrencyDTO));
I added a new class CryptoCurrencyService.

2023-02-19 19:18 UTC, lukaszkosminski commented on src/main/java/com/cryptoapp/controller/CurrencyController.java
> +        return currencyService.mapAndSave(currencyDTO);
I renamed this method to 'save', because in reality it only serves that purpose. I leave the DTO objects in services unchanged.

2023-02-19 19:20 UTC, lukaszkosminski commented on src/main/java/com/cryptoapp/controller/UserController.java
> +
done

2023-02-19 19:29 UTC, lukaszkosminski commented on src/main/java/com/cryptoapp/controller/UserController.java
> +    @PutMapping("user/{idUser}/change-email/{newEmail}")
Done, I used RequestBody

2023-02-19 19:30 UTC, lukaszkosminski commented on src/main/java/com/cryptoapp/controller/UserController.java
> +    @DeleteMapping("user/{idUser}/delete")
done

2023-02-19 19:41 UTC, lukaszkosminski commented on src/main/java/com/cryptoapp/controller/UserController.java
> +    @PostMapping("user/create")
done

2023-02-19 19:44 UTC, lukaszkosminski commented on src/main/java/com/cryptoapp/controller/UserController.java
> +
done

2023-02-19 19:44 UTC, lukaszkosminski commented on src/main/java/com/cryptoapp/controller/WalletController.java
> +
done

2023-02-19 19:48 UTC, lukaszkosminski commented on src/main/java/com/cryptoapp/dto/CryptoCurrencyDTO.java
> +
done

2023-02-19 19:48 UTC, lukaszkosminski commented on src/main/java/com/cryptoapp/dto/CryptoCurrencyDTO.java
> +
done

2023-02-19 19:48 UTC, lukaszkosminski commented on src/main/java/com/cryptoapp/model/CryptoCurrencyRate.java
> +    @CreationTimestamp
done

2023-02-19 20:19 UTC, lukaszkosminski commented on src/main/java/com/cryptoapp/service/CryptoCurrencyRateService.java
> +        String API_URL = String.format("https://min-api.cryptocompare.com/data/price?fsym=%s&tsyms=USD&api_key=57bf7cc844e4afd9d7ab7d87b7def9366f9208aa26f9d5d699662586b360cab1", symbol);
I saved the API_URL address as a constant with the private final access modifier. The API key is fetched from the application.properties file.

2023-02-19 20:44 UTC, lukaszkosminski commented on src/main/java/com/cryptoapp/service/CryptoCurrencyRateService.java
> +        List<CryptoCurrencyRateDTO> cryptoCurrencyRateDTOList = new ArrayList<>();
In this method, I create a list to which CryptoCurrencyRateDTO objects are added. For these objects in the list, the USD exchange rate will be obtained through an API. When my application is launched, this list is empty because there is no need to retrieve exchange rates.

To add an object to this list, a DTO object must be sent to the endpoint:
@PostMapping("/crypto/create")
public void create(@RequestBody CryptoCurrencyDTO cryptoCurrencyDTO) {
cryptoCurrencyService.save(cryptoCurrencyDTO);
}

2023-02-19 21:02 UTC, lukaszkosminski commented on src/main/java/com/cryptoapp/service/CurrencyService.java
> +    public CurrencyDTO addQuantity(Long id, Integer add) {
done

2023-02-19 21:03 UTC, lukaszkosminski commented on src/main/java/com/cryptoapp/service/CurrencyService.java
> +    public CurrencyDTO mapAndSave(CurrencyDTO currencyDTO) {
done

2023-02-20 17:26 UTC, lukaszkosminski commented on src/main/java/com/cryptoapp/service/CryptoCurrencyRateService.java
> +        String API_URL = String.format("https://min-api.cryptocompare.com/data/price?fsym=%s&tsyms=USD&api_key=57bf7cc844e4afd9d7ab7d87b7def9366f9208aa26f9d5d699662586b360cab1", symbol);
I also moved the API URL to the application.properties file

2023-02-20 18:05 UTC, lukaszkosminski commented on src/main/java/com/cryptoapp/controller/UserController.java
> +    @PutMapping("user/{idUser}/wallet/{idWallet}")
done

2023-02-20 18:07 UTC, lukaszkosminski commented on src/main/java/com/cryptoapp/controller/WalletController.java
> +        return walletService.getWalletList();
The endpoint has been removed.

2023-02-20 18:13 UTC, lukaszkosminski commented on src/main/java/com/cryptoapp/controller/WalletController.java
> +        return walletService.mapAndSave(walletDTO);
The wallet is being created and added to the user in this endpoint.
```
@PutMapping("user/{idUser}/wallet/")
```
This endpoint has been removed.
```
@PostMapping("/wallet")
```

2023-02-20 18:35 UTC, lukaszkosminski commented on src/main/java/com/cryptoapp/service/UserService.java
> +    public List<WalletDTO> getWalletByUser(Long idUser) {
done

2023-02-20 18:35 UTC, merged